### ISSUE TITLE
Were you able to get it working for latest react native version?

### ISSUE THREAD

**Issue by akashraj9828** [sourcetoad/react-native-queue#4]
I wanted to use this library but seems like the original library is not maintained anymore and it won't work on the new React native version.... so went diving into forks to see if anyone fixed it... you seem to have made a lot of changes so wondering if you got this library working again.

**Comment by iBotPeaches** [comment]
I somehow missed this message. Yes we use this library on an RN69 project. Haven't yet jumped to RN70, but if theres an issues when we do - we will update this
